checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - tests/*
        - 'bin/*'
        - 'config/*'
        - 'src/Helpers.php'
        - 'src/Config.php'
        - 'src/Exception/'
        - 'src/Support/'
        - 'src/Contract/'
build:
    tests:
        override:
            - command: ./vendor/bin/phpunit --verbose --coverage-text
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
