language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3

dist: trusty
sudo: false

before_script:
    - composer self-update
    - composer install --no-interaction --dev

script:
    - ./vendor/bin/phpunit --verbose --coverage-clover=coverage.xml

after_script:
    - bash <(curl -s https://codecov.io/bash)

matrix:
    fast_finish: true